# Site settings
title: Privacy Brief
email: privacybrief@protonmail.ch
description: > # this means to ignore newlines until "baseurl:"
  Your privacy in a surveillance society
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://privacybrief.github.io" # the base hostname & protocol for your site
twitter_username: privacybrief
github_username:  privacybrief

# Build settings
markdown: kramdown
