# Site settings
title: Privacy Brief
email: privacybrief@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/privacybrief" # the subpath of your site, e.g. /blog/
url: "https://h5hive.github.io/privacybrief" # the base hostname & protocol for your site
twitter_username: privacybrief
github_username:  privacybrief

# Build settings
markdown: kramdown
